using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using UnityEditor;
using Validosik.Core.Ioc;

namespace Validosik.Core.Editor.Ioc.CodeGeneration
{
    /// <summary>
    /// Emits per-container registry classes + central ContainerRegistryResolver index (runtime files).
    /// </summary>
    internal static class ContainerCodeGenerator
    {
        /// <summary>
        /// Emits all registries and a central index so runtime never scans assemblies.
        /// </summary>
        public static void EmitAll(
            string outputDir,
            IList<(string containerKey, IList<(Type iface, Type impl, ServiceLifetime lt, Type resolver)> bindings)>
                all)
        {
            if (string.IsNullOrEmpty(outputDir)) throw new ArgumentException(nameof(outputDir));
            Directory.CreateDirectory(outputDir);

            var emittedClassNames = new List<(string key, string className)>(all.Count);

            for (var i = 0; i < all.Count; ++i)
            {
                var (key, bindings) = all[i];
                var className = EmitRegistry(key, bindings, outputDir);
                emittedClassNames.Add((key, className));
            }

            EmitResolverIndex(outputDir, emittedClassNames);
            AssetDatabase.Refresh();
        }

        /// <returns>Generated runtime class name for this container</returns>
        private static string EmitRegistry(
            string containerKey,
            IList<(Type iface, Type impl, ServiceLifetime lt, Type resolver)> bindings,
            string outputDir)
        {
            if (string.IsNullOrEmpty(containerKey)) throw new ArgumentException(nameof(containerKey));
            if (string.IsNullOrEmpty(outputDir)) throw new ArgumentException(nameof(outputDir));
            Directory.CreateDirectory(outputDir);

            var className = SanitizeIdentifier(containerKey) + "_Registry";
            var path = Path.Combine(outputDir, className + ".g.cs");

            var sb = new StringBuilder(8 * 1024);
            sb.AppendLine("// <auto-generated /> DO NOT EDIT");
            sb.AppendLine("using System;");
            sb.AppendLine("using Validosik.Core.Ioc;");
            sb.AppendLine("using Validosik.Core.Ioc.Generated;");
            sb.AppendLine();
            sb.AppendLine("namespace Validosik.Core.Ioc.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Generated registry for container '" + Escape(containerKey) + "'</summary>");
            sb.AppendLine("    internal sealed class " + className + " : IGeneratedContainerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public string ContainerKey { get { return \"" + Escape(containerKey) + "\"; } }");
            sb.AppendLine("        public Binding[] GetBindings()");
            sb.AppendLine("        {");
            sb.AppendLine("            return new Binding[]");
            sb.AppendLine("            {");

            for (var i = 0; i < bindings.Count; ++i)
            {
                var b = bindings[i];
                var interfaceType = b.iface ?? throw new InvalidOperationException(
                    "Generated binding contains a null interface type for container '" + containerKey + "'.");
                if (b.resolver == null)
                {
                    var implementationType = b.impl ?? throw new InvalidOperationException(
                        "Generated binding contains a null implementation type for container '" + containerKey + "'.");
                    sb.Append("                new Binding(typeof(")
                        .Append(GetTypeReference(interfaceType)).Append("), typeof(")
                        .Append(GetTypeReference(implementationType)).Append("), ServiceLifetime.")
                        .Append(b.lt.ToString()).Append(")");
                }
                else
                {
                    var resolverType = b.resolver;
                    sb.Append("                new Binding(typeof(")
                        .Append(GetTypeReference(interfaceType)).Append("), typeof(")
                        .Append(GetTypeReference(resolverType)).Append("), ServiceLifetime.")
                        .Append(b.lt.ToString()).Append(", true)");
                }

                if (i + 1 < bindings.Count) sb.Append(",");
                sb.AppendLine();
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(RelativeToProject(path));
            return className;
        }

        private static void EmitResolverIndex(string outputDir, IList<(string key, string className)> registries)
        {
            var path = Path.Combine(outputDir, "ContainerRegistryResolver.g.cs");

            var sb = new StringBuilder(8 * 1024);
            sb.AppendLine("// <auto-generated /> DO NOT EDIT");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine();
            sb.AppendLine("namespace Validosik.Core.Ioc.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Central index of generated registries. Emitted by editor codegen;");
            sb.AppendLine("    /// Registers itself into ContainerRegistrySource without any reflection");
            sb.AppendLine("    /// No assembly scanning at runtime.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Preserve]");
            sb.AppendLine("    public static class ContainerRegistryResolver");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        private static readonly IGeneratedContainerRegistry[] _all = new IGeneratedContainerRegistry[]");
            sb.AppendLine("        {");
            for (var i = 0; i < registries.Count; ++i)
            {
                sb.Append("            new ").Append(registries[i].className).Append("()");
                if (i + 1 < registries.Count) sb.Append(",");
                sb.AppendLine();
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        static ContainerRegistryResolver()");
            sb.AppendLine("        {");
            sb.AppendLine("             // Hook into the package-side source");
            sb.AppendLine("             ContainerRegistrySource.Provider = () => _all;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine(
                "        // Unity will call this before scene load even if nobody touches the type explicitly.");
            sb.AppendLine(
                "        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        private static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("             // Ensure static ctor ran and Provider is set");
            sb.AppendLine("             _ = _all.Length;");
            sb.AppendLine("             ContainerRegistrySource.Provider = () => _all;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(RelativeToProject(path));
        }

        private static string SanitizeIdentifier(string key)
        {
            var sb = new StringBuilder(key.Length);
            for (var i = 0; i < key.Length; i++)
            {
                var c = key[i];
                if ((i == 0 && (c == '_' || char.IsLetter(c))) || (i > 0 && (char.IsLetterOrDigit(c) || c == '_')))
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            return sb.ToString();
        }

        private static string Escape(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string GetTypeReference(Type type)
        {
            if (type == null) throw new ArgumentNullException(nameof(type));
            return "global::" + (type.FullName ?? type.Name).Replace("+", ".");
        }

        private static string RelativeToProject(string abs)
        {
            var project = Path.GetFullPath(".");
            abs = Path.GetFullPath(abs);
            if (abs.StartsWith(project))
            {
                return abs.Substring(project.Length + (project.EndsWith("\\") ? 0 : 1)).Replace("\\", "/");
            }

            return abs.Replace("\\", "/");
        }
    }
}