using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using UnityEditor;
using Validosik.Core.Ioc;

namespace Validosik.Core.Editor.Ioc.CodeGeneration
{
    /// <summary>
    /// Emits a strongly-typed registry class per container
    /// </summary>
    internal static class ContainerCodeGenerator
    {
        public static void EmitRegistry(string containerKey,
            IList<(Type iface, Type impl, ServiceLifetime lt)> bindings, string outputDir)
        {
            if (string.IsNullOrEmpty(containerKey)) throw new ArgumentException("containerKey");
            if (string.IsNullOrEmpty(outputDir)) throw new ArgumentException("outputDir");
            Directory.CreateDirectory(outputDir);

            var className = SanitizeIdentifier(containerKey) + "_Registry";
            var path = Path.Combine(outputDir, className + ".g.cs");

            var sb = new StringBuilder(8 * 1024);
            sb.AppendLine("// <auto-generated /> DO NOT EDIT");
            sb.AppendLine("using System;");
            sb.AppendLine("using Validosik.Core.Ioc;");
            sb.AppendLine("using Validosik.Core.Ioc.Generated;");
            sb.AppendLine();
            sb.AppendLine("namespace Validosik.Core.Ioc.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Generated registry for container '" + containerKey + "'</summary>");
            sb.AppendLine("    internal sealed class " + className + " : IGeneratedContainerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public string ContainerKey { get { return \"" + Escape(containerKey) + "\"; } }");
            sb.AppendLine("        public Binding[] GetBindings()");
            sb.AppendLine("        {");
            sb.AppendLine("            return new Binding[]");
            sb.AppendLine("            {");

            for (var i = 0; i < bindings.Count; i++)
            {
                var b = bindings[i];
                sb.Append("                new Binding(typeof(")
                    .Append(b.iface.FullName).Append("), typeof(")
                    .Append(b.impl.FullName).Append("), ServiceLifetime.")
                    .Append(b.lt.ToString()).Append(")");
                if (i + 1 < bindings.Count) sb.Append(",");
                sb.AppendLine();
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(RelativeToProject(path));
        }

        private static string SanitizeIdentifier(string key)
        {
            var sb = new StringBuilder(key.Length);
            for (var i = 0; i < key.Length; i++)
            {
                var c = key[i];
                if (i == 0 && (c == '_' || char.IsLetter(c)))
                {
                    sb.Append(c);
                    continue;
                }

                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                    continue;
                }

                sb.Append('_');
            }

            return sb.ToString();
        }

        private static string Escape(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string RelativeToProject(string abs)
        {
            var project = Path.GetFullPath(".");
            abs = Path.GetFullPath(abs);
            if (abs.StartsWith(project))
                return abs.Substring(project.Length + (project.EndsWith("\\") ? 0 : 1)).Replace("\\", "/");
            return abs.Replace("\\", "/");
        }
    }
}